# name of the workflow
name: CI workflow

# triggers that starts the job (push and pull requests to/from main branch)
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # name of the job (i.e., jobname = "build")
  build:
    # runner for the job
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      # See: https://github.com/actions/checkout, https://graphite.dev/guides/github-actions-checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        # Pipe operator is used to run the following commands line-by-line in the same shell
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app


